# __Numpy__
- It is a general purpose array-processing package
- It provides high-performance multi-dimensional array objects and tools for working with these arrays

### __Arrays in Numpy__
- It is a table of elements of the same type, indexed by a tuple of positive integers
- Dimensions of array are called __axes__
- Number of axes in an array is called __rank__
- Numpy array class is called __ndarray__

### __Creating an array using Numpy methods__
- Numpy provides many functions to create arrays
1. __Using __array()__ function__
    - It is used to create a simple array from a list
    - data type can be defined by passing data type in dtype argument

In [ ]:
#Syntax
#import numpy as np
#array = np.array(<list>,dtype=int)

In [1]:
#Example 1: Creating a Basic Array
import numpy as np
array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [2]:
# Example 2: Creating a basic 2D array
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Example 3: Creating an array with specified type
import numpy as np
array = np.array([1,2,3,4],dtype=float)
print(array)
array2=np.array([1,2,3,4],dtype=str)
print(array2)


[1. 2. 3. 4.]
['1' '2' '3' '4']


2. __Creting an array using Numpy functions__
    - __zeros()__ function:
        - Creates an array filled with zeroes
        - Can take tuple as argument for multi-dimensional arrays

In [ ]:
#Syntax
#import numpy as np
#array = np.zeroes(shapes,dtype=float)

In [6]:
# Example 1: Creating a 1D array of zeroes of 5 size
array = np.zeros(5)
print(array)

[0. 0. 0. 0. 0.]


In [7]:
# Example 2: Creating a 2D array 
import numpy as np
array = np.zeros((3,4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# Example 3: Creating an array of zeroes with integer data type
import numpy as np
array = np.zeros((3,4),dtype=int)
print(array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


__ones()__ function
    - It creates an array filled with ones
    - shape can be tuple for multi-dimensional array

In [ ]:
#Syntax
#import numpy as np
# array = np.ones(shape,dtype=float)

In [10]:
# Example 1: Creating a 1d array of ones
import numpy as np
array = np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
# Example 2: Creating a 2d array of ones
import numpy as np
array = np.ones((3,4))
print(array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
# Example 3: Creating a 2d array of ones with different data type
import numpy as np
array = np.ones((3,4),dtype=int)
print(array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


- Using arange() function
    - It is similar to range() function but it returns a numpy array

In [ ]:
#Syntax:
#import numpy as np
# array=np.arange([start],stop,[step,]dtype=None)

In [14]:
#Example 1: Creating an array using only stop parameter
import numpy as np
array = np.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
# Example 2: Creating an array using start and stop parameter
import numpy as np
array = np.arange(5,15)
print(array)

[ 5  6  7  8  9 10 11 12 13 14]


In [17]:
# Example 3: Creating an array using start, stop and step parameter
import numpy as np
array = np.arange(10,20,2)
print(array)

[10 12 14 16 18]


In [19]:
#Example 4: Using negative step
import numpy as np
array= np.arange(11,0,-1)
print(array)

[11 10  9  8  7  6  5  4  3  2  1]


In [35]:
#Example 5: Using float
import numpy as np
array = np.arange(0,10,0.2,dtype=float)
print(array)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


- __linspace() function__
    - It is used to create an evenly spaced array between two intervals (start, stop)
    -  Unlike arange(), in linspace() you define the number of elements to be made between two intervals 

In [ ]:
#Syntax
#import numpy as np
#array = np.linspace(start,stop,num=50,endpoint=True,dtype=None)

In [22]:
# Example 1: Generating aray between 0 and 1
import numpy as np
array = np.linspace(0,1)
print(array)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [24]:
# Example 2: Creating an array of size 10 between 0 and 5
import numpy as np
array = np.linspace(0,5,num=10)
print(array)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [25]:
# Example 3: Excluding endpoint
import numpy as np
array = np.linspace(0,5,num=10,endpoint=False)
print(array)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [36]:
# Example 4: Specifying data type
import numpy as np
array = np.linspace(0,5,num=10,dtype=int)
print(array)

[0 0 1 1 2 2 3 3 4 4]


- __eye()__ function
    - It creates a 2D identity matrix
    - An identity matrix is a matrix with 1 in diagonal and zeros elsewhere

In [ ]:
#Syntax:
#import numpy as np
#array = np.eye(N,M=none,k=0,dtype=float)
#N: Number of rows in array
#M: Number of columns in array(Default is N)
#k: Starting index of diagonal(Default is 0)

In [29]:
#Example 1: Creating a basic identity matrix
import numpy as np
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
#Example 2:  Creating a rectangular matrix of 3x4
import numpy as np
R=np.eye(3,M=4)
print(R)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [31]:
# Example 3: Creating a matrix of 3x4 and diagonal shifted above main diagonal
import numpy as np
D=np.eye(3,M=4,k=1)
print(D)


[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
#Example 4: Creating a 3x4 matrix with diagonal shifted below main diagonal
import numpy as np
L= np.eye(3,M=3,k=-1)
print(L)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


### __Array Attribute and Methods__
- __min()__ function
    - Returns the minimum value in an array

In [ ]:
#Syntax: 
#import numpy as np
#min= np.min(array,axis=None)

In [37]:
#Example 1: min value from 1d array
import numpy as np
array=np.array([4,1,7,3])
min=min(array)
print(min)

1


In [39]:
#Example 2: Min value from 2d array
import numpy as np
array = np.array([[3,7,5],[8,4,2],[6,1,9]])
min = np.min(array)
print(min)

1


In [42]:
#Example 3: Min value of each column in 2d array
import numpy as np
array = np.array([[3,7,5],[8,4,2],[6,1,9]])
print(array)
min = np.min(array,axis=0)
print(min)

[[3 7 5]
 [8 4 2]
 [6 1 9]]
[3 1 2]


In [43]:
#Min value of each row in 2d array
import numpy as np
array = np.array([[3,7,5],[8,4,2],[6,1,9]])
print(array)
min = np.min(array,axis=1)
print(min)

[[3 7 5]
 [8 4 2]
 [6 1 9]]
[3 2 1]


- __max()__ function
    - It returns the max value from the array

In [ ]:
#Syntax: 
#import numpy as np
#max= np.max(array,axis=None)

In [44]:
#Example 1: Getting max value from 1D array
import numpy as np
array=np.array([4,1,7,3])
max=np.max(array)
print(max)

7


In [45]:
#Example 2: 
import numpy as np
array = np.array([[3,7,5],[8,4,2],[6,1,9]])
max=np.max(array)
print(max)

9


In [47]:
#Example 3: Getting max values from all columns
import numpy as np
array = np.array([[3,7,5],[8,4,2],[6,1,9]])
print(array)
max=np.max(array,axis=0)
print(max)

[[3 7 5]
 [8 4 2]
 [6 1 9]]
[8 7 9]


In [48]:
#Example 4: Getting max values from all rows
import numpy as np
array = np.array([[3,7,5],[8,4,2],[6,1,9]])
print(array)
max=np.max(array,axis=1)
print(max)

[[3 7 5]
 [8 4 2]
 [6 1 9]]
[7 8 9]


- __argmax()__ function
    - It returns the index of the max value in the array
    - If there are two occurences of a max value, first occurence in returned

In [ ]:
#Syntax
#import numpy as np
#i = np.argmax(array,axis=None)

In [49]:
#Example 1: Argmax of 1d array
import numpy as np
array=np.array([1,5,3,9,2])
index = np.argmax(array)
print(index)

3


In [52]:
# Example 2: Argmax in 2D array
import numpy as np
array = np.array([[10,15,30],[8,22,5],[3,25,50]])
index = np.argmax(array)
print(index)

8


In [53]:
#Example 3: Argmax column-wise
import numpy as np
array = np.array([[10,15,30],[8,22,5],[3,25,50]])
print(array)
index = np.argmax(array,axis=0)
print(index)

[[10 15 30]
 [ 8 22  5]
 [ 3 25 50]]
[0 2 2]


In [54]:
#Example 4: Argmax row-wise
import numpy as np
array = np.array([[10,15,30],[8,22,5],[3,25,50]])
print(array)
index = np.argmax(array,axis=1)
print(index)

[[10 15 30]
 [ 8 22  5]
 [ 3 25 50]]
[2 1 2]


- __argmin()__ function
    - It returns the index of the min value in the array
    - If there are two occurences of a min value, first occurence in returned

In [ ]:
#Syntax
#import numpy as np
#i = np.argmin(array,axis=None)

In [55]:
#Example 1: Argmin of 1d array
import numpy as np
array=np.array([1,5,3,9,2])
index = np.argmin(array)
print(index)

0


In [56]:
# Example 2: Argmin in 2D array
import numpy as np
array = np.array([[10,15,30],[8,22,5],[3,25,50]])
index = np.argmin(array)
print(index)

6


In [58]:
#Example 3: Argmax column-wise
import numpy as np
array = np.array([[10,15,30],[8,22,5],[3,25,50]])
print(array)
index = np.argmin(array,axis=0)
print(index)

[[10 15 30]
 [ 8 22  5]
 [ 3 25 50]]
[2 0 1]


In [59]:
#Example 4: Argmax row-wise
import numpy as np
array = np.array([[10,15,30],[8,22,5],[3,25,50]])
print(array)
index = np.argmin(array,axis=1)
print(index)

[[10 15 30]
 [ 8 22  5]
 [ 3 25 50]]
[0 2 0]


- __reshape()__ method
    - It is used to reshape an array
    - Useful when we have to change dimensions of a array without changing a data

In [ ]:
#Syntax
#import numpy as np
#array=np.reshape(array,newshape)

In [62]:
#Example 1: Reshaping a 1D array to 2D
import numpy as np
array = np.arange(12)
print(array)
array=np.reshape(array,(3,4))
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [63]:
#Example 2: Reshaping a 2x3 array into 3x2 array
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
print(array)
array=np.reshape(array,(3,2))
print(array)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [65]:
#Example 3: Automatically reshaping (using -1)
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
print(array)
array=np.reshape(array,(3,-1))
print(array)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


- __mean()__ function
    - It is used to return the mean of an array

In [ ]:
#Syntax:
#import numpy as np
#mean=np.mean(array,axis=None,dtype=float)

In [77]:
#Example 1: Calculating mean of 1D array
import numpy as np
array = np.array([1,2,3,4,5])
mean=np.mean(array)
print(mean)

3.0


In [79]:
#Example 2: Calculating mean of 2D array
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
mean=np.mean(array)
print(mean)

3.5


In [81]:
#Example 3: Calculating mean of 2D array column wise
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
print(array)
mean=np.mean(array,axis=0)
print(mean)

[[1 2 3]
 [4 5 6]]
[2.5 3.5 4.5]


In [84]:
#Example 4: Calculating mean of 2D array row wise
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
print(array)
mean=np.mean(array,axis=1)
print(mean)

[[1 2 3]
 [4 5 6]]
[2. 5.]


- __sum()__ function
    - It is used to compute the sum of the entire array

In [ ]:
#Syntax
#import numpy as np
#sum=np.sum(array,axis=None,dtype=None)

In [85]:
# Example 1: Calculating sum of 1D array
import numpy as np
array=np.array([1,2,3,4,5])
sum=np.sum(array)
print(sum)

15


In [86]:
#Example 2: Calculating sum of 2D array
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
sum=np.sum(array)
print(sum)

21


In [87]:
#Example 3: Calculating sum of 2D array column wise
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
sum=np.sum(array,axis=0)
print(sum)

[5 7 9]


In [88]:
#Example 4: Calculating sum of 2D array row wise
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
sum=np.sum(array,axis=1)
print(sum)

[ 6 15]


- __prod()__ function
    - It returns the product of every value in the array

In [ ]:
#Syntax
#import numpy as np
#product=np.prod(array,axis=None,dtype=None)

In [89]:
# Example 1: Calculating product of 1D array
import numpy as np
array=np.array([1,2,3,4,5])
product=np.prod(array)
print(product)

120


In [92]:
#Example 2: Calculating product of 2D array
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
product=np.prod(array)
print(product)

720


In [94]:
#Example 3: Calculating product of 2D array column wise
import numpy as np
array=np.array([[1,2,3],[4,5,6]])
print(array)
product=np.prod(array,axis=0)
print(product)

[[1 2 3]
 [4 5 6]]
[ 4 10 18]


In [99]:
#Example 4: Calculating product of 2D array row wise
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
print(array)
product=np.prod(array,axis=1)
print(product)

[[1 2 3]
 [4 5 6]]
[  6 120]


- __absolute()__ function
    - It is used to convert every value in array into positive

In [ ]:
#Syntax
#import numpy as np
#array=np.absolute(array,dtype=None)

In [100]:
#Example 1: Finding absolute of 1D array
import numpy as np
array = np.array([-1, -2, 3, -4, 5])
array = np.absolute(array)
print(array)


[1 2 3 4 5]


In [ ]:
#Example 2: Finding absolute of 2D array
import numpy as np


### __Broadcasting in Numpy__
- It is the ability of numpy to perform element-wise operations on array of different shapes, without explicitly copying the data
- Broadcasting is only possible if one of the arrays have size 1. If not, they should be the same size
- Trying to broadcast two arrays not compatible will raise in ValueError

In [67]:
#Example 1: Arithmetic between scalar and an array
import numpy as np
array = np.array([1,2,3])
A=array+5
B=array-5
C=array*5
D=array/5
print(A,B,C,D)

[6 7 8] [-4 -3 -2] [ 5 10 15] [0.2 0.4 0.6]


In [71]:
#Example 2: Broadcasting 1D array to 2D array
import numpy as np
array_1=np.array([10,20,30])
array_2=np.array([[100,200,300],[400,500,600]])
A=array_2+array_1
B=array_2-array_1
C=array_2*array_1
D=array_2/array_1
print(A,B,C,D,sep='\n')


[[110 220 330]
 [410 520 630]]
[[ 90 180 270]
 [390 480 570]]
[[ 1000  4000  9000]
 [ 4000 10000 18000]]
[[10. 10. 10.]
 [40. 25. 20.]]


In [73]:
#Example 3: Broadcasting array with different shapes
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
arr_broadcast = np.array([10, 20])
result = arr_3d + arr_broadcast
print(result)


[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]


### __Conditional Selection__
- Numpy allows you to filter arrays by specifying a condition using boolean/conditional operators

In [ ]:
#Syntax:
#import numpy as np
#filtered_array=array[condition]

In [75]:
#Example 1:
import numpy as np
array = np.array([10,15,25,30,35,40])

#Filter array with elements grater than 20
filtered_array=array[array>20]
print(filtered_array)

#Filter array with elements less than 27
filtered_array=array[array<27]
print(filtered_array)

[25 30 35 40]
[10 15 25]


In [76]:
#Example 2: Using multiple conditions
arr = np.array([10, 15, 20, 25, 30, 35, 40])
# Condition: Select elements greater than 15 and less than 35
filtered_arr = arr[(arr > 15) & (arr < 35)]
print("Elements greater than 15 and less than 35:", filtered_arr)


Elements greater than 15 and less than 35: [20 25 30]
